# Generated by Django 4.1.2 on 2022-10-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=250)),
                ('contactDetails', models.CharField(max_length=10)),
                ('banned', models.BooleanField()),
                ('approved', models.BooleanField()),
                ('type', models.CharField(choices=[('p', 'pharmacy'), ('h', 'hospital'), ('i', 'insurance firms')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('banned', models.BooleanField()),
                ('approved', models.BooleanField()),
                ('type', models.CharField(choices=[('p', 'patient'), ('h', 'health care professionals')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.organizations')),
            ],
        ),
    ]
