# Generated by Django 4.1.2 on 2022-10-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizations',
            new_name='Organization',
        ),
        migrations.RenameModel(
            old_name='OrganizationImages',
            new_name='OrganizationImage',
        ),
    ]
