# Generated by Django 4.1.2 on 2022-10-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_rename_organizations_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_proof', models.FileField(upload_to='documents/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='HCPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_proof', models.FileField(upload_to='documents/')),
                ('license_proof', models.FileField(upload_to='documents/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.user')),
            ],
        ),
    ]
