# Generated by Django 4.1.3 on 2022-11-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0006_user_orgname_pharmacyorder_insuranceclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('p', 'patient'), ('h', 'health care professionals'), ('a', 'admin'), ('r', 'pharmacy'), ('t', 'hospital'), ('i', 'insurance firms')], default='p', max_length=1),
        ),
    ]
