# Generated by Django 4.1.3 on 2022-11-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0008_remove_user_contactdetails_remove_user_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isUser',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('p', 'patient'), ('h', 'health care professionals'), ('a', 'admin')], default='p', max_length=1),
        ),
    ]
