# Generated by Django 4.1.3 on 2022-11-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0009_remove_user_isuser_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactDetails',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isUser',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orgName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('p', 'patient'), ('h', 'health care professionals'), ('a', 'admin'), ('r', 'pharmacy'), ('t', 'hospital'), ('i', 'insurance firms')], default='p', max_length=1),
        ),
    ]
