# Generated by Django 4.1.3 on 2022-11-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0010_user_contactdetails_user_description_user_isuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
