# Generated by Django 4.1.3 on 2022-11-26 17:26

from django.db import migrations, models
import patient_management.validator


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='cipher',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[patient_management.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[patient_management.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='hcpdocument',
            name='identity_proof',
            field=models.FileField(upload_to='documents/', validators=[patient_management.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='hcpdocument',
            name='license_proof',
            field=models.FileField(upload_to='documents/', validators=[patient_management.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='organizationimage',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[patient_management.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='pdocument',
            name='identity_proof',
            field=models.FileField(upload_to='documents/', validators=[patient_management.validator.validate_file_size]),
        ),
    ]
