# Generated by Django 4.1.3 on 2022-11-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0012_file_verified_alter_file_cipher_alter_file_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='expire',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='InsuranceClaim',
        ),
    ]
