# Generated by Django 4.1.3 on 2022-11-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0013_tokens_expire_alter_user_name_delete_insuranceclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expire',
            field=models.PositiveBigIntegerField(),
        ),
    ]
