# Generated by Django 4.1.3 on 2022-11-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0014_alter_tokens_expire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
